title: Prajakta Amate # your name (or website title) here
logo: "images/img1.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  👋 Hi everyone!  📊 I love diving into data to find interesting insights! 💡 
  With skills in SQL,Tableau , Excel I turn numbers into useful information.
  🚀 Take a look at my work to see how I make sense of data and use it to solve problems. Let's explore the world of data together! 🌟
  <br><br> 
  <a href="https://www.linkedin.com/in/prajaktaamate/"> Connect With Me: LinkedIn Profile</a>
  <a href="files/Prajakta_Amate_Resume.pdf"> Resume </a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
